version: "3.7"
services:
  app:
    container_name: uyi-web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
